spring.application.name=review-service
# --- SERVER ---
server.port=8080

# --- DATABASE H2 ---
spring.datasource.url=jdbc:h2:mem:reviewdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.platform=h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- JPA / HIBERNATE ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# --- LOGGING ---
logging.level.org.springframework.web=DEBUG
logging.level.com.review.service=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
